# Generated by Django 5.0.4 on 2024-04-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='design',
            new_name='description',
        ),
    ]
