# Generated by Django 5.0.4 on 2024-04-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_design_order_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='design',
        ),
    ]
